# Generated by Django 3.1.1 on 2020-10-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_inscription', models.DateTimeField(verbose_name="date d'inscription ")),
                ('auteur_favori', models.CharField(max_length=200)),
                ('livre_favori', models.CharField(max_length=200)),
            ],
        ),
    ]
