# Generated by Django 3.1.1 on 2020-10-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste_livre', models.CharField(max_length=200)),
                ('liste_saga', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_saga', models.CharField(max_length=200)),
                ('nb_de_tome', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('nb_de_mots', models.IntegerField(default=0)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classementLivre.auteur')),
                ('saga', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classementLivre.saga')),
            ],
        ),
        migrations.CreateModel(
            name='ListeDeLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_de_livre', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(verbose_name=' date de création ')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classementLivre.livre')),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='liste_de_lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='classementLivre.listedelecture'),
            preserve_default=False,
        ),
    ]
