# Generated by Django 3.1.1 on 2020-10-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0002_auto_20201005_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auteur',
            name='liste_livre',
        ),
        migrations.RemoveField(
            model_name='auteur',
            name='liste_saga',
        ),
        migrations.RemoveField(
            model_name='listedelecture',
            name='nb_de_livre',
        ),
    ]
