# Generated by Django 3.1.1 on 2020-10-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0003_auto_20201005_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='auteur_favori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classementLivre.auteur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='livre_favori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classementLivre.livre'),
        ),
    ]
