# Generated by Django 3.1.1 on 2020-10-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0004_auto_20201005_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
