# Generated by Django 3.1.1 on 2020-10-07 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0005_utilisateur_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='saga',
            field=models.ForeignKey(default='livre unique', on_delete=django.db.models.deletion.DO_NOTHING, to='classementLivre.saga'),
        ),
    ]
