# Generated by Django 3.1.1 on 2020-10-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0006_auto_20201007_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='avis',
            field=models.TextField(default="Pas d'avis"),
        ),
    ]
