# Generated by Django 3.1.1 on 2020-10-07 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0007_livre_avis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('titre_avis', models.CharField(max_length=200)),
                ('commentaire', models.TextField()),
                ('date_avis', models.DateTimeField(verbose_name="date de l'avis")),
            ],
        ),
        migrations.AlterField(
            model_name='livre',
            name='avis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classementLivre.avis'),
        ),
    ]
