# Generated by Django 3.1.1 on 2020-10-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0008_auto_20201007_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='date_avis',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
