# Generated by Django 3.1.1 on 2020-10-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0009_auto_20201007_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listedelecture',
            name='livre',
        ),
        migrations.AddField(
            model_name='livre',
            name='liste_de_lecture',
            field=models.ManyToManyField(to='classementLivre.ListeDeLecture'),
        ),
    ]
