# Generated by Django 3.1.1 on 2020-10-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0010_auto_20201008_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='liste_de_lecture',
        ),
        migrations.AddField(
            model_name='listedelecture',
            name='livre',
            field=models.ManyToManyField(to='classementLivre.Livre'),
        ),
    ]
