# Generated by Django 3.1.1 on 2020-10-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0011_auto_20201008_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='avis',
        ),
        migrations.AddField(
            model_name='livre',
            name='avis',
            field=models.ManyToManyField(to='classementLivre.Avis'),
        ),
    ]
