# Generated by Django 3.1.1 on 2020-10-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0012_auto_20201008_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='avis',
        ),
        migrations.AddField(
            model_name='avis',
            name='livre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classementLivre.livre'),
            preserve_default=False,
        ),
    ]
