# Generated by Django 3.1.1 on 2020-10-08 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0013_auto_20201008_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='livre',
        ),
        migrations.AddField(
            model_name='livre',
            name='avis',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='classementLivre.avis'),
            preserve_default=False,
        ),
    ]
