# Generated by Django 3.1.1 on 2020-10-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0015_auto_20201008_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='avis',
        ),
    ]
