# Generated by Django 3.1.1 on 2020-10-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0016_remove_livre_avis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='titre',
        ),
        migrations.AddField(
            model_name='avis',
            name='livre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='classementLivre.livre'),
            preserve_default=False,
        ),
    ]
