# Generated by Django 3.1.1 on 2020-10-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0017_auto_20201008_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='slug',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='liste_de_lecture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='classementLivre.listedelecture'),
        ),
    ]
