# Generated by Django 3.1.1 on 2020-10-09 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0019_auto_20201008_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='livre',
            new_name='livre_avis',
        ),
        migrations.AddField(
            model_name='livre',
            name='avis_livre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='classementLivre.avis'),
            preserve_default=False,
        ),
    ]
