# Generated by Django 3.1.1 on 2020-10-09 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0020_auto_20201009_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='livre_avis',
            new_name='avis_livre',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='auteur',
            new_name='livre_auteur',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='avis_livre',
            new_name='livre_avis',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='saga',
            new_name='livre_saga',
        ),
        migrations.AddField(
            model_name='auteur',
            name='auteur_livre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='classementLivre.livre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saga',
            name='saga_livre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='classementLivre.livre'),
            preserve_default=False,
        ),
    ]
