# Generated by Django 3.1.1 on 2020-10-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0021_auto_20201009_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auteur',
            old_name='auteur_livre',
            new_name='livre_auteur',
        ),
        migrations.RenameField(
            model_name='avis',
            old_name='avis_livre',
            new_name='livre_avis',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='livre_auteur',
            new_name='auteur_livre',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='livre_avis',
            new_name='avis_livre',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='livre_saga',
            new_name='saga_livre',
        ),
        migrations.RenameField(
            model_name='saga',
            old_name='saga_livre',
            new_name='livre_saga',
        ),
    ]
