# Generated by Django 3.1.1 on 2020-10-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classementLivre', '0022_auto_20201009_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='livre_saga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='classementLivre.saga'),
            preserve_default=False,
        ),
    ]
